import { afterEach, beforeEach, describe, expect, it, mock, spyOn } from 'bun:test';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { parse as parseDotenv } from 'dotenv';

const cancelToken = Symbol('cancel');

let multiselectAnswers: unknown[] = [];
let selectAnswers: unknown[] = [];
let confirmAnswers: unknown[] = [];
let textAnswers: unknown[] = [];
let passwordAnswers: unknown[] = [];

const promptMock = {
  intro: mock((_message: string) => {}),
  outro: mock((_message: string) => {}),
  note: mock((_message: string, _title?: string) => {}),
  cancel: mock((_message: string) => {}),
  isCancel: (value: unknown) => value === cancelToken,
  multiselect: mock(async () => multiselectAnswers.shift()),
  select: mock(async () => selectAnswers.shift()),
  confirm: mock(async () => confirmAnswers.shift()),
  text: mock(async () => textAnswers.shift()),
  password: mock(async () => passwordAnswers.shift()),
  spinner: mock(() => ({
    start: mock((_message: string) => {}),
    stop: mock((_message?: string) => {}),
  })),
  log: {
    info: mock((_message: string) => {}),
    warning: mock((_message: string) => {}),
    success: mock((_message: string) => {}),
    warn: mock((_message: string) => {}),
  },
};

mock.module('@clack/prompts', () => promptMock);
const { setupCommand } = await import('./setup');

function resetPromptMocks(): void {
  multiselectAnswers = [];
  selectAnswers = [];
  confirmAnswers = [];
  textAnswers = [];
  passwordAnswers = [];
  promptMock.intro.mockClear();
  promptMock.outro.mockClear();
  promptMock.note.mockClear();
  promptMock.cancel.mockClear();
  promptMock.multiselect.mockClear();
  promptMock.select.mockClear();
  promptMock.confirm.mockClear();
  promptMock.text.mockClear();
  promptMock.password.mockClear();
  promptMock.spinner.mockClear();
  promptMock.log.info.mockClear();
  promptMock.log.warning.mockClear();
  promptMock.log.success.mockClear();
  promptMock.log.warn.mockClear();
}

describe('setupCommand interactive characterization', () => {
  let root: string;
  let home: string;
  let repo: string;
  let originalArchonHome: string | undefined;
  let originalHome: string | undefined;
  let exitSpy: ReturnType<typeof spyOn>;

  beforeEach(() => {
    resetPromptMocks();
    root = mkdtempSync(join(tmpdir(), 'archon-setup-command-'));
    home = join(root, 'home');
    repo = join(root, 'repo');
    mkdirSync(home, { recursive: true });
    mkdirSync(repo, { recursive: true });
    originalArchonHome = process.env.ARCHON_HOME;
    originalHome = process.env.HOME;
    process.env.ARCHON_HOME = home;
    process.env.HOME = home;
    exitSpy = spyOn(process, 'exit').mockImplementation(((code?: string | number | null) => {
      throw new Error(`process.exit:${code}`);
    }) as typeof process.exit);
  });

  afterEach(() => {
    exitSpy.mockRestore();
    if (originalArchonHome === undefined) delete process.env.ARCHON_HOME;
    else process.env.ARCHON_HOME = originalArchonHome;
    if (originalHome === undefined) delete process.env.HOME;
    else process.env.HOME = originalHome;
    rmSync(root, { recursive: true, force: true });
  });

  it('writes project-scoped fresh CLI-only config without assistant credentials or skill install', async () => {
    multiselectAnswers = [[], []];
    confirmAnswers = [false, false, false, false];

    await setupCommand({ repoPath: repo, scope: 'project', force: false });

    const envPath = join(repo, '.archon', '.env');
    expect(readFileSync(envPath, 'utf-8')).toBe(
      [
        '# Archon Configuration',
        '# Generated by `archon setup`',
        '',
        '# Database',
        '# Using SQLite (default) - no DATABASE_URL needed',
        '# Set DATABASE_URL=postgresql://... to use PostgreSQL instead.',
        '',
        '# AI Assistants',
        '# Claude not configured',
        '',
        '# Pi not configured',
        '',
        '# Default AI Assistant',
        'DEFAULT_AI_ASSISTANT=claude',
        '',
        '# Server',
        '# PORT=3090  # Default: 3090. Uncomment to override.',
        '',
        '# Concurrency',
        'MAX_CONCURRENT_CONVERSATIONS=10',
      ].join('\n')
    );
    expect(existsSync(join(repo, '.claude', 'skills', 'archon'))).toBe(false);
    expect(promptMock.confirm).toHaveBeenCalledTimes(4);
    expect(promptMock.outro).toHaveBeenCalledWith('Setup complete!');
  });

  it('add mode preserves existing assistant config while adding only newly selected platform credentials', async () => {
    const archonDir = join(repo, '.archon');
    mkdirSync(archonDir, { recursive: true });
    writeFileSync(
      join(archonDir, '.env'),
      'CLAUDE_USE_GLOBAL_AUTH=true\nTELEGRAM_BOT_TOKEN=123:existing\nCUSTOM_KEY=keep\n'
    );
    selectAnswers = ['add'];
    multiselectAnswers = [['slack']];
    passwordAnswers = ['xoxb-new-token', 'xapp-new-token'];
    textAnswers = ['U123,U456'];
    confirmAnswers = [false, false, false];

    await setupCommand({ repoPath: repo, scope: 'project', force: false });

    const parsed = parseDotenv(readFileSync(join(archonDir, '.env'), 'utf-8'));
    expect(parsed.CLAUDE_USE_GLOBAL_AUTH).toBe('true');
    expect(parsed.TELEGRAM_BOT_TOKEN).toBe('123:existing');
    expect(parsed.CUSTOM_KEY).toBe('keep');
    expect(parsed.SLACK_BOT_TOKEN).toBe('xoxb-new-token');
    expect(parsed.SLACK_APP_TOKEN).toBe('xapp-new-token');
    expect(parsed.SLACK_ALLOWED_USER_IDS).toBe('U123,U456');
    expect(parsed.DEFAULT_AI_ASSISTANT).toBe('claude');
  });

  it('cancels before writing config when assistant selection is cancelled', async () => {
    multiselectAnswers = [cancelToken];

    await expect(setupCommand({ repoPath: repo, scope: 'project', force: false })).rejects.toThrow(
      'process.exit:0'
    );

    expect(promptMock.cancel).toHaveBeenCalledWith('Setup cancelled.');
    expect(existsSync(join(repo, '.archon', '.env'))).toBe(false);
  });
});
